[[redirects]]
from = "/fi/yarns/lettlopi/colors/availability"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/fi/patterns/riddari/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/yarns/lettlopi/colors/availability"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/patterns/riddari/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/"
to = "/fi/"
status = 200
force = true
