[[redirects]]
from = "/fi/patterns/sweaters/simple/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/fi/patterns/sweaters/multicolor/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/patterns/sweaters/simple/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/patterns/sweaters/multicolor/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/"
to = "/fi/"
status = 200
force = true

[[redirects]]
from = "/fi/colors/availability/*"
to = "/fi/patterns/riddari/colors/:splat"
status = 301
force = true

[[redirects]]
from = "/en/colors/availability/*"
to = "/en/patterns/riddari/colors/:splat"
status = 301
force = true

[[redirects]]
from = "/fi/colors/*"
to = "/fi/patterns/riddari/colors/:splat"
status = 301
force = true

[[redirects]]
from = "/en/colors/*"
to = "/en/patterns/riddari/colors/:splat"
status = 301
force = true

[[redirects]]
from = "/en/patterns/*"
to = "/en/"
status = 301
force = true

[[redirects]]
from = "/fi/patterns/*"
to = "/fi/"
status = 301
force = true
