[[redirects]]
from = "/fi/riddari/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/fi/lettlopi/colors/availability"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/riddari/colors/"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/lettlopi/colors/availability"
to = "/.netlify/functions/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/"
to = "/fi/"
status = 200
force = true
