[[redirects]]
from = "/fi/yarns/lettlopi/availability/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/fi/patterns/riddari/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/fi/patterns/riddari-multiple/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/yarns/lettlopi/availability/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/patterns/riddari/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/en/patterns/riddari-multiple/colors/"
to = "/.netlify/builders/colors"
status = 200
force = true
_generated_by_eleventy_serverless = "colors"

[[redirects]]
from = "/"
to = "/fi/"
status = 200
force = true

[[redirects]]
from = "/fi/colors/"
to = "/fi/patterns/riddari/colors/"
status = 200
force = true

[[redirects]]
from = "/en/colors/"
to = "/en/patterns/riddari/colors/"
status = 200
force = true
