name: Get Stock


on:
  workflow_dispatch:

jobs:
  get-stock:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feat/show-where-to-get-yarns
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install

      - name: Update stock
        run: npm run updateStock

      - name: Commit changes
        run: |
          git config --global user.email "updater-bot"
          git config --global user.name "updater-bot"
          git add .
          git commit -a -m "Update stock"
          git push origin feat/show-where-to-get-yarns
