name: Get Stock

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  get-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm install
      - name: Secret to File
        uses: MobileDevOps/secret-to-file-action@v1.0.0
        with:
          base64-encoded-secret: ${{ secrets.FILE_CONTENT }}
          filename: "service-account.json"
      - name: Update stock
        run: npm run updateStock

      - name: Commit changes
        run: |
          git config --global user.email "updater-bot"
          git config --global user.name "updater-bot"
          git add .
          git commit -a -m "Update stock"
          git push origin main
