name: Get Stock

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  get-stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install

      - name: Update stock
        run: npm run updateStock
        env: 
          FC_CLIENT_EMAIL: ${{ secrets.FC_CLIENT_EMAIL }}
          FC_PROJECT_ID: ${{ secrets.FC_PROJECT_ID }}
          FC_PRIVATE_KEY: ${{ secrets.FC_PRIVATE_KEY }}
      - name: Commit changes
        run: |
          git config --global user.email "updater-bot"
          git config --global user.name "updater-bot"
          git add .
          git commit -a -m "Update stock"
          git push origin main
